version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    env_file: .env
    # local development
    command: npm run dev
    working_dir: /usr/bin/app
    volumes: 
      - ./:/usr/bin/app:cached