version: '3.7'
services:
  db:
    image: 'postgres:11.5'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_MULTIPLE_DATABASES=devdb,db2
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=psw
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3005:3005'
    env_file: .env
    # local development
    depends_on:
      - 'db'
    command: ['./bin/wait-for-it.sh', 'db', 'npm', 'run', 'dev']
    working_dir: /usr/bin/app
    volumes:
      - ./:/usr/bin/app:cached
